-- 商品主题

USE gmall;

insert overwrite table dwt_sku_topic partition (dt = '2021-06-16')
select id,
       nvl(order_last_1d_count, 0),
       nvl(order_last_1d_num, 0),
       nvl(order_activity_last_1d_count, 0),
       nvl(order_coupon_last_1d_count, 0),
       nvl(order_activity_reduce_last_1d_amount, 0),
       nvl(order_coupon_reduce_last_1d_amount, 0),
       nvl(order_last_1d_original_amount, 0),
       nvl(order_last_1d_final_amount, 0),
       nvl(order_last_7d_count, 0),
       nvl(order_last_7d_num, 0),
       nvl(order_activity_last_7d_count, 0),
       nvl(order_coupon_last_7d_count, 0),
       nvl(order_activity_reduce_last_7d_amount, 0),
       nvl(order_coupon_reduce_last_7d_amount, 0),
       nvl(order_last_7d_original_amount, 0),
       nvl(order_last_7d_final_amount, 0),
       nvl(order_last_30d_count, 0),
       nvl(order_last_30d_num, 0),
       nvl(order_activity_last_30d_count, 0),
       nvl(order_coupon_last_30d_count, 0),
       nvl(order_activity_reduce_last_30d_amount, 0),
       nvl(order_coupon_reduce_last_30d_amount, 0),
       nvl(order_last_30d_original_amount, 0),
       nvl(order_last_30d_final_amount, 0),
       nvl(order_count, 0),
       nvl(order_num, 0),
       nvl(order_activity_count, 0),
       nvl(order_coupon_count, 0),
       nvl(order_activity_reduce_amount, 0),
       nvl(order_coupon_reduce_amount, 0),
       nvl(order_original_amount, 0),
       nvl(order_final_amount, 0),
       nvl(payment_last_1d_count, 0),
       nvl(payment_last_1d_num, 0),
       nvl(payment_last_1d_amount, 0),
       nvl(payment_last_7d_count, 0),
       nvl(payment_last_7d_num, 0),
       nvl(payment_last_7d_amount, 0),
       nvl(payment_last_30d_count, 0),
       nvl(payment_last_30d_num, 0),
       nvl(payment_last_30d_amount, 0),
       nvl(payment_count, 0),
       nvl(payment_num, 0),
       nvl(payment_amount, 0),
       nvl(refund_order_last_1d_count, 0),
       nvl(refund_order_last_1d_num, 0),
       nvl(refund_order_last_1d_amount, 0),
       nvl(refund_order_last_7d_count, 0),
       nvl(refund_order_last_7d_num, 0),
       nvl(refund_order_last_7d_amount, 0),
       nvl(refund_order_last_30d_count, 0),
       nvl(refund_order_last_30d_num, 0),
       nvl(refund_order_last_30d_amount, 0),
       nvl(refund_order_count, 0),
       nvl(refund_order_num, 0),
       nvl(refund_order_amount, 0),
       nvl(refund_payment_last_1d_count, 0),
       nvl(refund_payment_last_1d_num, 0),
       nvl(refund_payment_last_1d_amount, 0),
       nvl(refund_payment_last_7d_count, 0),
       nvl(refund_payment_last_7d_num, 0),
       nvl(refund_payment_last_7d_amount, 0),
       nvl(refund_payment_last_30d_count, 0),
       nvl(refund_payment_last_30d_num, 0),
       nvl(refund_payment_last_30d_amount, 0),
       nvl(refund_payment_count, 0),
       nvl(refund_payment_num, 0),
       nvl(refund_payment_amount, 0),
       nvl(cart_last_1d_count, 0),
       nvl(cart_last_7d_count, 0),
       nvl(cart_last_30d_count, 0),
       nvl(cart_count, 0),
       nvl(favor_last_1d_count, 0),
       nvl(favor_last_7d_count, 0),
       nvl(favor_last_30d_count, 0),
       nvl(favor_count, 0),
       nvl(appraise_last_1d_good_count, 0),
       nvl(appraise_last_1d_mid_count, 0),
       nvl(appraise_last_1d_bad_count, 0),
       nvl(appraise_last_1d_default_count, 0),
       nvl(appraise_last_7d_good_count, 0),
       nvl(appraise_last_7d_mid_count, 0),
       nvl(appraise_last_7d_bad_count, 0),
       nvl(appraise_last_7d_default_count, 0),
       nvl(appraise_last_30d_good_count, 0),
       nvl(appraise_last_30d_mid_count, 0),
       nvl(appraise_last_30d_bad_count, 0),
       nvl(appraise_last_30d_default_count, 0),
       nvl(appraise_good_count, 0),
       nvl(appraise_mid_count, 0),
       nvl(appraise_bad_count, 0),
       nvl(appraise_default_count, 0)
from (
         select id
         from dim_sku_info
         where dt = '2021-06-16'
     ) t1
         left join
     (
         select sku_id,
                sum(if(dt = '2021-06-16', order_count, 0))                                    order_last_1d_count,
                sum(if(dt = '2021-06-16', order_num, 0))                                      order_last_1d_num,
                sum(if(dt = '2021-06-16', order_activity_count, 0))                           order_activity_last_1d_count,
                sum(if(dt = '2021-06-16', order_coupon_count, 0))                             order_coupon_last_1d_count,
                sum(if(dt = '2021-06-16', order_activity_reduce_amount, 0))                   order_activity_reduce_last_1d_amount,
                sum(if(dt = '2021-06-16', order_coupon_reduce_amount, 0))                     order_coupon_reduce_last_1d_amount,
                sum(if(dt = '2021-06-16', order_original_amount, 0))                          order_last_1d_original_amount,
                sum(if(dt = '2021-06-16', order_final_amount, 0))                             order_last_1d_final_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_count, 0))                     order_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), order_num, 0))                       order_last_7d_num,
                sum(if(dt >= date_add('2021-06-16', -6), order_activity_count, 0))            order_activity_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), order_coupon_count, 0))              order_coupon_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), order_activity_reduce_amount,
                       0))                                                                    order_activity_reduce_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -6), order_coupon_reduce_amount, 0))  order_coupon_reduce_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -6), order_original_amount, 0))       order_last_7d_original_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_final_amount, 0))              order_last_7d_final_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_count, 0))                    order_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), order_num, 0))                      order_last_30d_num,
                sum(
                        if(dt >= date_add('2021-06-16', -29), order_activity_count, 0))       order_activity_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), order_coupon_count, 0))             order_coupon_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), order_activity_reduce_amount,
                       0))                                                                    order_activity_reduce_last_30d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -29), order_coupon_reduce_amount, 0)) order_coupon_reduce_last_30d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -29), order_original_amount, 0))      order_last_30d_original_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_final_amount, 0))             order_last_30d_final_amount,
                sum(order_count)                                                              order_count,
                sum(order_num)                                                                order_num,
                sum(order_activity_count)                                                     order_activity_count,
                sum(order_coupon_count)                                                       order_coupon_count,
                sum(order_activity_reduce_amount)                                             order_activity_reduce_amount,
                sum(order_coupon_reduce_amount)                                               order_coupon_reduce_amount,
                sum(order_original_amount)                                                    order_original_amount,
                sum(order_final_amount)                                                       order_final_amount,
                sum(if(dt = '2021-06-16', payment_count, 0))                                  payment_last_1d_count,
                sum(if(dt = '2021-06-16', payment_num, 0))                                    payment_last_1d_num,
                sum(if(dt = '2021-06-16', payment_amount, 0))                                 payment_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), payment_count, 0))                   payment_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), payment_num, 0))                     payment_last_7d_num,
                sum(if(dt >= date_add('2021-06-16', -6), payment_amount, 0))                  payment_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), payment_count, 0))                  payment_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), payment_num, 0))                    payment_last_30d_num,
                sum(if(dt >= date_add('2021-06-16', -29), payment_amount, 0))                 payment_last_30d_amount,
                sum(payment_count)                                                            payment_count,
                sum(payment_num)                                                              payment_num,
                sum(payment_amount)                                                           payment_amount,
                sum(if(dt = '2021-06-16', refund_order_count, 0))                             refund_order_last_1d_count,
                sum(if(dt = '2021-06-16', refund_order_num, 0))                               refund_order_last_1d_num,
                sum(if(dt = '2021-06-16', refund_order_amount, 0))                            refund_order_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_count, 0))              refund_order_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_num, 0))                refund_order_last_7d_num,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_amount, 0))             refund_order_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_count, 0))             refund_order_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_num, 0))               refund_order_last_30d_num,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_amount, 0))            refund_order_last_30d_amount,
                sum(refund_order_count)                                                       refund_order_count,
                sum(refund_order_num)                                                         refund_order_num,
                sum(refund_order_amount)                                                      refund_order_amount,
                sum(if(dt = '2021-06-16', refund_payment_count, 0))                           refund_payment_last_1d_count,
                sum(if(dt = '2021-06-16', refund_payment_num, 0))                             refund_payment_last_1d_num,
                sum(if(dt = '2021-06-16', refund_payment_amount, 0))                          refund_payment_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), refund_payment_count, 0))            refund_payment_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), refund_payment_num, 0))              refund_payment_last_7d_num,
                sum(
                        if(dt >= date_add('2021-06-16', -6), refund_payment_amount, 0))       refund_payment_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -29), refund_payment_count, 0))       refund_payment_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), refund_payment_num, 0))             refund_payment_last_30d_num,
                sum(
                        if(dt >= date_add('2021-06-16', -29), refund_payment_amount, 0))      refund_payment_last_30d_amount,
                sum(refund_payment_count)                                                     refund_payment_count,
                sum(refund_payment_num)                                                       refund_payment_num,
                sum(refund_payment_amount)                                                    refund_payment_amount,
                sum(if(dt = '2021-06-16', cart_count, 0))                                     cart_last_1d_count,
                sum(if(dt >= date_add('2021-06-16', -6), cart_count, 0))                      cart_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -29), cart_count, 0))                     cart_last_30d_count,
                sum(cart_count)                                                               cart_count,
                sum(if(dt = '2021-06-16', favor_count, 0))                                    favor_last_1d_count,
                sum(if(dt >= date_add('2021-06-16', -6), favor_count, 0))                     favor_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -29), favor_count, 0))                    favor_last_30d_count,
                sum(favor_count)                                                              favor_count,
                sum(if(dt = '2021-06-16', appraise_good_count, 0))                            appraise_last_1d_good_count,
                sum(if(dt = '2021-06-16', appraise_mid_count, 0))                             appraise_last_1d_mid_count,
                sum(if(dt = '2021-06-16', appraise_bad_count, 0))                             appraise_last_1d_bad_count,
                sum(if(dt = '2021-06-16', appraise_default_count, 0))                         appraise_last_1d_default_count,
                sum(if(dt >= date_add('2021-06-16', -6), appraise_good_count, 0))             appraise_last_7d_good_count,
                sum(if(dt >= date_add('2021-06-16', -6), appraise_mid_count, 0))              appraise_last_7d_mid_count,
                sum(if(dt >= date_add('2021-06-16', -6), appraise_bad_count, 0))              appraise_last_7d_bad_count,
                sum(
                        if(dt >= date_add('2021-06-16', -6), appraise_default_count, 0))      appraise_last_7d_default_count,
                sum(if(dt >= date_add('2021-06-16', -29), appraise_good_count, 0))            appraise_last_30d_good_count,
                sum(if(dt >= date_add('2021-06-16', -29), appraise_mid_count, 0))             appraise_last_30d_mid_count,
                sum(if(dt >= date_add('2021-06-16', -29), appraise_bad_count, 0))             appraise_last_30d_bad_count,
                sum(
                        if(dt >= date_add('2021-06-16', -29), appraise_default_count, 0))     appraise_last_30d_default_count,
                sum(appraise_good_count)                                                      appraise_good_count,
                sum(appraise_mid_count)                                                       appraise_mid_count,
                sum(appraise_bad_count)                                                       appraise_bad_count,
                sum(appraise_default_count)                                                   appraise_default_count
         from dws_sku_action_daycount
         group by sku_id
     ) t2
     on t1.id = t2.sku_id;
