-- 用户主题

USE gmall;

insert overwrite table dwt_user_topic partition (dt = '2021-06-16')
select id,
       login_date_first,--以用户的创建日期作为首次登录日期
       nvl(login_date_last, date_add('2021-06-16', -1)),--若有历史登录记录，则根据历史记录获取末次登录日期，否则统一指定一个日期
       nvl(login_last_1d_count, 0),
       nvl(login_last_1d_day_count, 0),
       nvl(login_last_7d_count, 0),
       nvl(login_last_7d_day_count, 0),
       nvl(login_last_30d_count, 0),
       nvl(login_last_30d_day_count, 0),
       nvl(login_count, 0),
       nvl(login_day_count, 0),
       order_date_first,
       order_date_last,
       nvl(order_last_1d_count, 0),
       nvl(order_activity_last_1d_count, 0),
       nvl(order_activity_reduce_last_1d_amount, 0),
       nvl(order_coupon_last_1d_count, 0),
       nvl(order_coupon_reduce_last_1d_amount, 0),
       nvl(order_last_1d_original_amount, 0),
       nvl(order_last_1d_final_amount, 0),
       nvl(order_last_7d_count, 0),
       nvl(order_activity_last_7d_count, 0),
       nvl(order_activity_reduce_last_7d_amount, 0),
       nvl(order_coupon_last_7d_count, 0),
       nvl(order_coupon_reduce_last_7d_amount, 0),
       nvl(order_last_7d_original_amount, 0),
       nvl(order_last_7d_final_amount, 0),
       nvl(order_last_30d_count, 0),
       nvl(order_activity_last_30d_count, 0),
       nvl(order_activity_reduce_last_30d_amount, 0),
       nvl(order_coupon_last_30d_count, 0),
       nvl(order_coupon_reduce_last_30d_amount, 0),
       nvl(order_last_30d_original_amount, 0),
       nvl(order_last_30d_final_amount, 0),
       nvl(order_count, 0),
       nvl(order_activity_count, 0),
       nvl(order_activity_reduce_amount, 0),
       nvl(order_coupon_count, 0),
       nvl(order_coupon_reduce_amount, 0),
       nvl(order_original_amount, 0),
       nvl(order_final_amount, 0),
       payment_date_first,
       payment_date_last,
       nvl(payment_last_1d_count, 0),
       nvl(payment_last_1d_amount, 0),
       nvl(payment_last_7d_count, 0),
       nvl(payment_last_7d_amount, 0),
       nvl(payment_last_30d_count, 0),
       nvl(payment_last_30d_amount, 0),
       nvl(payment_count, 0),
       nvl(payment_amount, 0),
       nvl(refund_order_last_1d_count, 0),
       nvl(refund_order_last_1d_num, 0),
       nvl(refund_order_last_1d_amount, 0),
       nvl(refund_order_last_7d_count, 0),
       nvl(refund_order_last_7d_num, 0),
       nvl(refund_order_last_7d_amount, 0),
       nvl(refund_order_last_30d_count, 0),
       nvl(refund_order_last_30d_num, 0),
       nvl(refund_order_last_30d_amount, 0),
       nvl(refund_order_count, 0),
       nvl(refund_order_num, 0),
       nvl(refund_order_amount, 0),
       nvl(refund_payment_last_1d_count, 0),
       nvl(refund_payment_last_1d_num, 0),
       nvl(refund_payment_last_1d_amount, 0),
       nvl(refund_payment_last_7d_count, 0),
       nvl(refund_payment_last_7d_num, 0),
       nvl(refund_payment_last_7d_amount, 0),
       nvl(refund_payment_last_30d_count, 0),
       nvl(refund_payment_last_30d_num, 0),
       nvl(refund_payment_last_30d_amount, 0),
       nvl(refund_payment_count, 0),
       nvl(refund_payment_num, 0),
       nvl(refund_payment_amount, 0),
       nvl(cart_last_1d_count, 0),
       nvl(cart_last_7d_count, 0),
       nvl(cart_last_30d_count, 0),
       nvl(cart_count, 0),
       nvl(favor_last_1d_count, 0),
       nvl(favor_last_7d_count, 0),
       nvl(favor_last_30d_count, 0),
       nvl(favor_count, 0),
       nvl(coupon_last_1d_get_count, 0),
       nvl(coupon_last_1d_using_count, 0),
       nvl(coupon_last_1d_used_count, 0),
       nvl(coupon_last_7d_get_count, 0),
       nvl(coupon_last_7d_using_count, 0),
       nvl(coupon_last_7d_used_count, 0),
       nvl(coupon_last_30d_get_count, 0),
       nvl(coupon_last_30d_using_count, 0),
       nvl(coupon_last_30d_used_count, 0),
       nvl(coupon_get_count, 0),
       nvl(coupon_using_count, 0),
       nvl(coupon_used_count, 0),
       nvl(appraise_last_1d_good_count, 0),
       nvl(appraise_last_1d_mid_count, 0),
       nvl(appraise_last_1d_bad_count, 0),
       nvl(appraise_last_1d_default_count, 0),
       nvl(appraise_last_7d_good_count, 0),
       nvl(appraise_last_7d_mid_count, 0),
       nvl(appraise_last_7d_bad_count, 0),
       nvl(appraise_last_7d_default_count, 0),
       nvl(appraise_last_30d_good_count, 0),
       nvl(appraise_last_30d_mid_count, 0),
       nvl(appraise_last_30d_bad_count, 0),
       nvl(appraise_last_30d_default_count, 0),
       nvl(appraise_good_count, 0),
       nvl(appraise_mid_count, 0),
       nvl(appraise_bad_count, 0),
       nvl(appraise_default_count, 0)
from (
         select id,
                date_format(create_time, 'yyyy-MM-dd') login_date_first
         from dim_user_info
         where dt = '9999-99-99'
     ) t1
         left join
     (
         select user_id                                                                       user_id,
                max(dt)                                                                       login_date_last,
                sum(if(dt = '2021-06-16', login_count, 0))                                    login_last_1d_count,
                sum(if(dt = '2021-06-16' and login_count > 0, 1, 0))                          login_last_1d_day_count,
                sum(if(dt >= date_add('2021-06-16', -6), login_count, 0))                     login_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6) and login_count > 0, 1, 0))           login_last_7d_day_count,
                sum(if(dt >= date_add('2021-06-16', -29), login_count, 0))                    login_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29) and login_count > 0, 1, 0))          login_last_30d_day_count,
                sum(login_count)                                                              login_count,
                sum(if(login_count > 0, 1, 0))                                                login_day_count,
                min(if(order_count > 0, dt, null))                                            order_date_first,
                max(if(order_count > 0, dt, null))                                            order_date_last,
                sum(if(dt = '2021-06-16', order_count, 0))                                    order_last_1d_count,
                sum(if(dt = '2021-06-16', order_activity_count, 0))                           order_activity_last_1d_count,
                sum(if(dt = '2021-06-16', order_activity_reduce_amount, 0))                   order_activity_reduce_last_1d_amount,
                sum(if(dt = '2021-06-16', order_coupon_count, 0))                             order_coupon_last_1d_count,
                sum(if(dt = '2021-06-16', order_coupon_reduce_amount, 0))                     order_coupon_reduce_last_1d_amount,
                sum(if(dt = '2021-06-16', order_original_amount, 0))                          order_last_1d_original_amount,
                sum(if(dt = '2021-06-16', order_final_amount, 0))                             order_last_1d_final_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_count, 0))                     order_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), order_activity_count, 0))            order_activity_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), order_activity_reduce_amount,
                       0))                                                                    order_activity_reduce_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_coupon_count, 0))              order_coupon_last_7d_count,
                sum(
                        if(dt >= date_add('2021-06-16', -6), order_coupon_reduce_amount, 0))  order_coupon_reduce_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -6), order_original_amount, 0))       order_last_7d_original_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_final_amount, 0))              order_last_7d_final_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_count, 0))                    order_last_30d_count,
                sum(
                        if(dt >= date_add('2021-06-16', -29), order_activity_count, 0))       order_activity_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), order_activity_reduce_amount,
                       0))                                                                    order_activity_reduce_last_30d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_coupon_count, 0))             order_coupon_last_30d_count,
                sum(
                        if(dt >= date_add('2021-06-16', -29), order_coupon_reduce_amount, 0)) order_coupon_reduce_last_30d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -29), order_original_amount, 0))      order_last_30d_original_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_final_amount, 0))             order_last_30d_final_amount,
                sum(order_count)                                                              order_count,
                sum(order_activity_count)                                                     order_activity_count,
                sum(order_activity_reduce_amount)                                             order_activity_reduce_amount,
                sum(order_coupon_count)                                                       order_coupon_count,
                sum(order_coupon_reduce_amount)                                               order_coupon_reduce_amount,
                sum(order_original_amount)                                                    order_original_amount,
                sum(order_final_amount)                                                       order_final_amount,
                min(if(payment_count > 0, dt, null))                                          payment_date_first,
                max(if(payment_count > 0, dt, null))                                          payment_date_last,
                sum(if(dt = '2021-06-16', payment_count, 0))                                  payment_last_1d_count,
                sum(if(dt = '2021-06-16', payment_amount, 0))                                 payment_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), payment_count, 0))                   payment_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), payment_amount, 0))                  payment_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), payment_count, 0))                  payment_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), payment_amount, 0))                 payment_last_30d_amount,
                sum(payment_count)                                                            payment_count,
                sum(payment_amount)                                                           payment_amount,
                sum(if(dt = '2021-06-16', refund_order_count, 0))                             refund_order_last_1d_count,
                sum(if(dt = '2021-06-16', refund_order_num, 0))                               refund_order_last_1d_num,
                sum(if(dt = '2021-06-16', refund_order_amount, 0))                            refund_order_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_count, 0))              refund_order_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_num, 0))                refund_order_last_7d_num,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_amount, 0))             refund_order_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_count, 0))             refund_order_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_num, 0))               refund_order_last_30d_num,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_amount, 0))            refund_order_last_30d_amount,
                sum(refund_order_count)                                                       refund_order_count,
                sum(refund_order_num)                                                         refund_order_num,
                sum(refund_order_amount)                                                      refund_order_amount,
                sum(if(dt = '2021-06-16', refund_payment_count, 0))                           refund_payment_last_1d_count,
                sum(if(dt = '2021-06-16', refund_payment_num, 0))                             refund_payment_last_1d_num,
                sum(if(dt = '2021-06-16', refund_payment_amount, 0))                          refund_payment_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), refund_payment_count, 0))            refund_payment_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), refund_payment_num, 0))              refund_payment_last_7d_num,
                sum(
                        if(dt >= date_add('2021-06-16', -6), refund_payment_amount, 0))       refund_payment_last_7d_amount,
                sum(
                        if(dt >= date_add('2021-06-16', -29), refund_payment_count, 0))       refund_payment_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), refund_payment_num, 0))             refund_payment_last_30d_num,
                sum(
                        if(dt >= date_add('2021-06-16', -29), refund_payment_amount, 0))      refund_payment_last_30d_amount,
                sum(refund_payment_count)                                                     refund_payment_count,
                sum(refund_payment_num)                                                       refund_payment_num,
                sum(refund_payment_amount)                                                    refund_payment_amount,
                sum(if(dt = '2021-06-16', cart_count, 0))                                     cart_last_1d_count,
                sum(if(dt >= date_add('2021-06-16', -6), cart_count, 0))                      cart_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -29), cart_count, 0))                     cart_last_30d_count,
                sum(cart_count)                                                               cart_count,
                sum(if(dt = '2021-06-16', favor_count, 0))                                    favor_last_1d_count,
                sum(if(dt >= date_add('2021-06-16', -6), favor_count, 0))                     favor_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -29), favor_count, 0))                    favor_last_30d_count,
                sum(favor_count)                                                              favor_count,
                sum(if(dt = '2021-06-16', coupon_get_count, 0))                               coupon_last_1d_get_count,
                sum(if(dt = '2021-06-16', coupon_using_count, 0))                             coupon_last_1d_using_count,
                sum(if(dt = '2021-06-16', coupon_used_count, 0))                              coupon_last_1d_used_count,
                sum(if(dt >= date_add('2021-06-16', -6), coupon_get_count, 0))                coupon_last_7d_get_count,
                sum(if(dt >= date_add('2021-06-16', -6), coupon_using_count, 0))              coupon_last_7d_using_count,
                sum(if(dt >= date_add('2021-06-16', -6), coupon_used_count, 0))               coupon_last_7d_used_count,
                sum(if(dt >= date_add('2021-06-16', -29), coupon_get_count, 0))               coupon_last_30d_get_count,
                sum(if(dt >= date_add('2021-06-16', -29), coupon_using_count, 0))             coupon_last_30d_using_count,
                sum(if(dt >= date_add('2021-06-16', -29), coupon_used_count, 0))              coupon_last_30d_used_count,
                sum(coupon_get_count)                                                         coupon_get_count,
                sum(coupon_using_count)                                                       coupon_using_count,
                sum(coupon_used_count)                                                        coupon_used_count,
                sum(if(dt = '2021-06-16', appraise_good_count, 0))                            appraise_last_1d_good_count,
                sum(if(dt = '2021-06-16', appraise_mid_count, 0))                             appraise_last_1d_mid_count,
                sum(if(dt = '2021-06-16', appraise_bad_count, 0))                             appraise_last_1d_bad_count,
                sum(if(dt = '2021-06-16', appraise_default_count, 0))                         appraise_last_1d_default_count,
                sum(if(dt >= date_add('2021-06-16', -6), appraise_good_count, 0))             appraise_last_7d_good_count,
                sum(if(dt >= date_add('2021-06-16', -6), appraise_mid_count, 0))              appraise_last_7d_mid_count,
                sum(if(dt >= date_add('2021-06-16', -6), appraise_bad_count, 0))              appraise_last_7d_bad_count,
                sum(
                        if(dt >= date_add('2021-06-16', -6), appraise_default_count, 0))      appraise_last_7d_default_count,
                sum(if(dt >= date_add('2021-06-16', -29), appraise_good_count, 0))            appraise_last_30d_good_count,
                sum(if(dt >= date_add('2021-06-16', -29), appraise_mid_count, 0))             appraise_last_30d_mid_count,
                sum(if(dt >= date_add('2021-06-16', -29), appraise_bad_count, 0))             appraise_last_30d_bad_count,
                sum(
                        if(dt >= date_add('2021-06-16', -29), appraise_default_count, 0))     appraise_last_30d_default_count,
                sum(appraise_good_count)                                                      appraise_good_count,
                sum(appraise_mid_count)                                                       appraise_mid_count,
                sum(appraise_bad_count)                                                       appraise_bad_count,
                sum(appraise_default_count)                                                   appraise_default_count
         from dws_user_action_daycount
         group by user_id
     ) t2
     on t1.id = t2.user_id;
