-- 用户主题

USE gmall;

insert overwrite table dwt_user_topic partition(dt='2021-06-17')
select
    nvl(1d_ago.user_id,old.user_id),
    nvl(old.login_date_first,'2021-06-17'),
    if(1d_ago.user_id is not null,'2021-06-17',old.login_date_last),
    nvl(1d_ago.login_count,0),
    if(1d_ago.user_id is not null,1,0),
    nvl(old.login_last_7d_count,0)+nvl(1d_ago.login_count,0)- nvl(7d_ago.login_count,0),
    nvl(old.login_last_7d_day_count,0)+if(1d_ago.user_id is null,0,1)- if(7d_ago.user_id is null,0,1),
    nvl(old.login_last_30d_count,0)+nvl(1d_ago.login_count,0)- nvl(30d_ago.login_count,0),
    nvl(old.login_last_30d_day_count,0)+if(1d_ago.user_id is null,0,1)- if(30d_ago.user_id is null,0,1),
    nvl(old.login_count,0)+nvl(1d_ago.login_count,0),
    nvl(old.login_day_count,0)+if(1d_ago.user_id is not null,1,0),
    if(old.order_date_first is null and 1d_ago.order_count>0, '2021-06-17', old.order_date_first),
    if(1d_ago.order_count>0,'2021-06-17',old.order_date_last),
    nvl(1d_ago.order_count,0),
    nvl(1d_ago.order_activity_count,0),
    nvl(1d_ago.order_activity_reduce_amount,0.0),
    nvl(1d_ago.order_coupon_count,0),
    nvl(1d_ago.order_coupon_reduce_amount,0.0),
    nvl(1d_ago.order_original_amount,0.0),
    nvl(1d_ago.order_final_amount,0.0),
    nvl(old.order_last_7d_count,0)+nvl(1d_ago.order_count,0)- nvl(7d_ago.order_count,0),
    nvl(old.order_activity_last_7d_count,0)+nvl(1d_ago.order_activity_count,0)- nvl(7d_ago.order_activity_count,0),
    nvl(old.order_activity_reduce_last_7d_amount,0.0)+nvl(1d_ago.order_activity_reduce_amount,0.0)- nvl(7d_ago.order_activity_reduce_amount,0.0),
    nvl(old.order_coupon_last_7d_count,0)+nvl(1d_ago.order_coupon_count,0)- nvl(7d_ago.order_coupon_count,0),
    nvl(old.order_coupon_reduce_last_7d_amount,0.0)+nvl(1d_ago.order_coupon_reduce_amount,0.0)- nvl(7d_ago.order_coupon_reduce_amount,0.0),
    nvl(old.order_last_7d_original_amount,0.0)+nvl(1d_ago.order_original_amount,0.0)- nvl(7d_ago.order_original_amount,0.0),
    nvl(old.order_last_7d_final_amount,0.0)+nvl(1d_ago.order_final_amount,0.0)- nvl(7d_ago.order_final_amount,0.0),
    nvl(old.order_last_30d_count,0)+nvl(1d_ago.order_count,0)- nvl(30d_ago.order_count,0),
    nvl(old.order_activity_last_30d_count,0)+nvl(1d_ago.order_activity_count,0)- nvl(30d_ago.order_activity_count,0),
    nvl(old.order_activity_reduce_last_30d_amount,0.0)+nvl(1d_ago.order_activity_reduce_amount,0.0)- nvl(30d_ago.order_activity_reduce_amount,0.0),
    nvl(old.order_coupon_last_30d_count,0)+nvl(1d_ago.order_coupon_count,0)- nvl(30d_ago.order_coupon_count,0),
    nvl(old.order_coupon_reduce_last_30d_amount,0.0)+nvl(1d_ago.order_coupon_reduce_amount,0.0)- nvl(30d_ago.order_coupon_reduce_amount,0.0),
    nvl(old.order_last_30d_original_amount,0.0)+nvl(1d_ago.order_original_amount,0.0)- nvl(30d_ago.order_original_amount,0.0),
    nvl(old.order_last_30d_final_amount,0.0)+nvl(1d_ago.order_final_amount,0.0)- nvl(30d_ago.order_final_amount,0.0),
    nvl(old.order_count,0)+nvl(1d_ago.order_count,0),
    nvl(old.order_activity_count,0)+nvl(1d_ago.order_activity_count,0),
    nvl(old.order_activity_reduce_amount,0.0)+nvl(1d_ago.order_activity_reduce_amount,0.0),
    nvl(old.order_coupon_count,0)+nvl(1d_ago.order_coupon_count,0),
    nvl(old.order_coupon_reduce_amount,0.0)+nvl(1d_ago.order_coupon_reduce_amount,0.0),
    nvl(old.order_original_amount,0.0)+nvl(1d_ago.order_original_amount,0.0),
    nvl(old.order_final_amount,0.0)+nvl(1d_ago.order_final_amount,0.0),
    if(old.payment_date_first is null and 1d_ago.payment_count>0, '2021-06-17', old.payment_date_first),
    if(1d_ago.payment_count>0,'2021-06-17',old.payment_date_last),
    nvl(1d_ago.payment_count,0),
    nvl(1d_ago.payment_amount,0.0),
    nvl(old.payment_last_7d_count,0)+nvl(1d_ago.payment_count,0)-nvl(7d_ago.payment_count,0),
    nvl(old.payment_last_7d_amount,0.0)+nvl(1d_ago.payment_amount,0.0)-nvl(7d_ago.payment_amount,0.0),
    nvl(old.payment_last_30d_count,0)+nvl(1d_ago.payment_count,0)-nvl(30d_ago.payment_count,0),
    nvl(old.payment_last_30d_amount,0.0)+nvl(1d_ago.payment_amount,0.0)- nvl(30d_ago.payment_amount,0.0),
    nvl(old.payment_count,0)+nvl(1d_ago.payment_count,0),
    nvl(old.payment_amount,0.0)+nvl(1d_ago.payment_amount,0.0),
    nvl(1d_ago.refund_order_count,0),
    nvl(1d_ago.refund_order_num,0),
    nvl(1d_ago.refund_order_amount,0.0),
    nvl(old.refund_order_last_7d_count,0)+nvl(1d_ago.refund_order_count,0)- nvl(7d_ago.refund_order_count,0),
    nvl(old.refund_order_last_7d_num,0)+nvl(1d_ago.refund_order_num, 0)- nvl(7d_ago.refund_order_num,0),
    nvl(old.refund_order_last_7d_amount,0.0)+ nvl(1d_ago.refund_order_amount,0.0)- nvl(7d_ago.refund_order_amount,0.0),
    nvl(old.refund_order_last_30d_count,0)+nvl(1d_ago.refund_order_count,0)- nvl(30d_ago.refund_order_count,0),
    nvl(old.refund_order_last_30d_num,0)+nvl(1d_ago.refund_order_num, 0)- nvl(30d_ago.refund_order_num,0),
    nvl(old.refund_order_last_30d_amount,0.0)+ nvl(1d_ago.refund_order_amount,0.0)- nvl(30d_ago.refund_order_amount,0.0),
    nvl(old.refund_order_count,0)+nvl(1d_ago.refund_order_count,0),
    nvl(old.refund_order_num,0)+nvl(1d_ago.refund_order_num,0),
    nvl(old.refund_order_amount,0.0)+ nvl(1d_ago.refund_order_amount,0.0),
    nvl(1d_ago.refund_payment_count,0),
    nvl(1d_ago.refund_payment_num,0),
    nvl(1d_ago.refund_payment_amount,0.0),
    nvl(old.refund_payment_last_7d_count,0)+nvl(1d_ago.refund_payment_count,0)-nvl(7d_ago.refund_payment_count,0),
    nvl(old.refund_payment_last_7d_num,0)+nvl(1d_ago.refund_payment_num,0)- nvl(7d_ago.refund_payment_num,0),
    nvl(old.refund_payment_last_7d_amount,0.0)+ nvl(1d_ago.refund_payment_amount,0.0)- nvl(7d_ago.refund_payment_amount,0.0),
    nvl(old.refund_payment_last_30d_count,0)+nvl(1d_ago.refund_payment_count,0)-nvl(30d_ago.refund_payment_count,0),
    nvl(old.refund_payment_last_30d_num,0)+nvl(1d_ago.refund_payment_num,0)- nvl(30d_ago.refund_payment_num,0),
    nvl(old.refund_payment_last_30d_amount,0.0)+ nvl(1d_ago.refund_payment_amount,0.0)- nvl(30d_ago.refund_payment_amount,0.0),
    nvl(old.refund_payment_count,0)+nvl(1d_ago.refund_payment_count,0),
    nvl(old.refund_payment_num,0)+nvl(1d_ago.refund_payment_num,0),
    nvl(old.refund_payment_amount,0.0)+nvl(1d_ago.refund_payment_amount,0.0),
    nvl(1d_ago.cart_count,0),
    nvl(old.cart_last_7d_count,0)+nvl(1d_ago.cart_count,0)-nvl(7d_ago.cart_count,0),
    nvl(old.cart_last_30d_count,0)+nvl(1d_ago.cart_count,0)-nvl(30d_ago.cart_count,0),
    nvl(old.cart_count,0)+nvl(1d_ago.cart_count,0),
    nvl(1d_ago.favor_count,0),
    nvl(old.favor_last_7d_count,0)+nvl(1d_ago.favor_count,0)- nvl(7d_ago.favor_count,0),
    nvl(old.favor_last_30d_count,0)+nvl(1d_ago.favor_count,0)- nvl(30d_ago.favor_count,0),
    nvl(old.favor_count,0)+nvl(1d_ago.favor_count,0),
    nvl(1d_ago.coupon_get_count,0),
    nvl(1d_ago.coupon_using_count,0),
    nvl(1d_ago.coupon_used_count,0),
    nvl(old.coupon_last_7d_get_count,0)+nvl(1d_ago.coupon_get_count,0)- nvl(7d_ago.coupon_get_count,0),
    nvl(old.coupon_last_7d_using_count,0)+nvl(1d_ago.coupon_using_count,0)- nvl(7d_ago.coupon_using_count,0),
    nvl(old.coupon_last_7d_used_count,0)+ nvl(1d_ago.coupon_used_count,0)- nvl(7d_ago.coupon_used_count,0),
    nvl(old.coupon_last_30d_get_count,0)+nvl(1d_ago.coupon_get_count,0)- nvl(30d_ago.coupon_get_count,0),
    nvl(old.coupon_last_30d_using_count,0)+nvl(1d_ago.coupon_using_count,0)- nvl(30d_ago.coupon_using_count,0),
    nvl(old.coupon_last_30d_used_count,0)+ nvl(1d_ago.coupon_used_count,0)- nvl(30d_ago.coupon_used_count,0),
    nvl(old.coupon_get_count,0)+nvl(1d_ago.coupon_get_count,0),
    nvl(old.coupon_using_count,0)+nvl(1d_ago.coupon_using_count,0),
    nvl(old.coupon_used_count,0)+nvl(1d_ago.coupon_used_count,0),
    nvl(1d_ago.appraise_good_count,0),
    nvl(1d_ago.appraise_mid_count,0),
    nvl(1d_ago.appraise_bad_count,0),
    nvl(1d_ago.appraise_default_count,0),
    nvl(old.appraise_last_7d_good_count,0)+nvl(1d_ago.appraise_good_count,0)- nvl(7d_ago.appraise_good_count,0),
    nvl(old.appraise_last_7d_mid_count,0)+nvl(1d_ago.appraise_mid_count,0)-nvl(7d_ago.appraise_mid_count,0),
    nvl(old.appraise_last_7d_bad_count,0)+nvl(1d_ago.appraise_bad_count,0)-nvl(7d_ago.appraise_bad_count,0),
    nvl(old.appraise_last_7d_default_count,0)+nvl(1d_ago.appraise_default_count,0)-nvl(7d_ago.appraise_default_count,0),
    nvl(old.appraise_last_30d_good_count,0)+nvl(1d_ago.appraise_good_count,0)- nvl(30d_ago.appraise_good_count,0),
    nvl(old.appraise_last_30d_mid_count,0)+nvl(1d_ago.appraise_mid_count,0)-nvl(30d_ago.appraise_mid_count,0),
    nvl(old.appraise_last_30d_bad_count,0)+nvl(1d_ago.appraise_bad_count,0)-nvl(30d_ago.appraise_bad_count,0),
    nvl(old.appraise_last_30d_default_count,0)+nvl(1d_ago.appraise_default_count,0)-nvl(30d_ago.appraise_default_count,0),
    nvl(old.appraise_good_count,0)+nvl(1d_ago.appraise_good_count,0),
    nvl(old.appraise_mid_count,0)+nvl(1d_ago.appraise_mid_count, 0),
    nvl(old.appraise_bad_count,0)+nvl(1d_ago.appraise_bad_count,0),
    nvl(old.appraise_default_count,0)+nvl(1d_ago.appraise_default_count,0)
from
    (
        select
            user_id,
            login_date_first,
            login_date_last,
            login_date_1d_count,
            login_last_1d_day_count,
            login_last_7d_count,
            login_last_7d_day_count,
            login_last_30d_count,
            login_last_30d_day_count,
            login_count,
            login_day_count,
            order_date_first,
            order_date_last,
            order_last_1d_count,
            order_activity_last_1d_count,
            order_activity_reduce_last_1d_amount,
            order_coupon_last_1d_count,
            order_coupon_reduce_last_1d_amount,
            order_last_1d_original_amount,
            order_last_1d_final_amount,
            order_last_7d_count,
            order_activity_last_7d_count,
            order_activity_reduce_last_7d_amount,
            order_coupon_last_7d_count,
            order_coupon_reduce_last_7d_amount,
            order_last_7d_original_amount,
            order_last_7d_final_amount,
            order_last_30d_count,
            order_activity_last_30d_count,
            order_activity_reduce_last_30d_amount,
            order_coupon_last_30d_count,
            order_coupon_reduce_last_30d_amount,
            order_last_30d_original_amount,
            order_last_30d_final_amount,
            order_count,
            order_activity_count,
            order_activity_reduce_amount,
            order_coupon_count,
            order_coupon_reduce_amount,
            order_original_amount,
            order_final_amount,
            payment_date_first,
            payment_date_last,
            payment_last_1d_count,
            payment_last_1d_amount,
            payment_last_7d_count,
            payment_last_7d_amount,
            payment_last_30d_count,
            payment_last_30d_amount,
            payment_count,
            payment_amount,
            refund_order_last_1d_count,
            refund_order_last_1d_num,
            refund_order_last_1d_amount,
            refund_order_last_7d_count,
            refund_order_last_7d_num,
            refund_order_last_7d_amount,
            refund_order_last_30d_count,
            refund_order_last_30d_num,
            refund_order_last_30d_amount,
            refund_order_count,
            refund_order_num,
            refund_order_amount,
            refund_payment_last_1d_count,
            refund_payment_last_1d_num,
            refund_payment_last_1d_amount,
            refund_payment_last_7d_count,
            refund_payment_last_7d_num,
            refund_payment_last_7d_amount,
            refund_payment_last_30d_count,
            refund_payment_last_30d_num,
            refund_payment_last_30d_amount,
            refund_payment_count,
            refund_payment_num,
            refund_payment_amount,
            cart_last_1d_count,
            cart_last_7d_count,
            cart_last_30d_count,
            cart_count,
            favor_last_1d_count,
            favor_last_7d_count,
            favor_last_30d_count,
            favor_count,
            coupon_last_1d_get_count,
            coupon_last_1d_using_count,
            coupon_last_1d_used_count,
            coupon_last_7d_get_count,
            coupon_last_7d_using_count,
            coupon_last_7d_used_count,
            coupon_last_30d_get_count,
            coupon_last_30d_using_count,
            coupon_last_30d_used_count,
            coupon_get_count,
            coupon_using_count,
            coupon_used_count,
            appraise_last_1d_good_count,
            appraise_last_1d_mid_count,
            appraise_last_1d_bad_count,
            appraise_last_1d_default_count,
            appraise_last_7d_good_count,
            appraise_last_7d_mid_count,
            appraise_last_7d_bad_count,
            appraise_last_7d_default_count,
            appraise_last_30d_good_count,
            appraise_last_30d_mid_count,
            appraise_last_30d_bad_count,
            appraise_last_30d_default_count,
            appraise_good_count,
            appraise_mid_count,
            appraise_bad_count,
            appraise_default_count
        from dwt_user_topic
        where dt=date_add('2021-06-17',-1)
    )old
        full outer join
    (
        select
            user_id,
            login_count,
            cart_count,
            favor_count,
            order_count,
            order_activity_count,
            order_activity_reduce_amount,
            order_coupon_count,
            order_coupon_reduce_amount,
            order_original_amount,
            order_final_amount,
            payment_count,
            payment_amount,
            refund_order_count,
            refund_order_num,
            refund_order_amount,
            refund_payment_count,
            refund_payment_num,
            refund_payment_amount,
            coupon_get_count,
            coupon_using_count,
            coupon_used_count,
            appraise_good_count,
            appraise_mid_count,
            appraise_bad_count,
            appraise_default_count
        from dws_user_action_daycount
        where dt='2021-06-17'
    )1d_ago
    on old.user_id=1d_ago.user_id
        left join
    (
        select
            user_id,
            login_count,
            cart_count,
            favor_count,
            order_count,
            order_activity_count,
            order_activity_reduce_amount,
            order_coupon_count,
            order_coupon_reduce_amount,
            order_original_amount,
            order_final_amount,
            payment_count,
            payment_amount,
            refund_order_count,
            refund_order_num,
            refund_order_amount,
            refund_payment_count,
            refund_payment_num,
            refund_payment_amount,
            coupon_get_count,
            coupon_using_count,
            coupon_used_count,
            appraise_good_count,
            appraise_mid_count,
            appraise_bad_count,
            appraise_default_count
        from dws_user_action_daycount
        where dt=date_add('2021-06-17',-7)
    )7d_ago
    on old.user_id=7d_ago.user_id
        left join
    (
        select
            user_id,
            login_count,
            cart_count,
            favor_count,
            order_count,
            order_activity_count,
            order_activity_reduce_amount,
            order_coupon_count,
            order_coupon_reduce_amount,
            order_original_amount,
            order_final_amount,
            payment_count,
            payment_amount,
            refund_order_count,
            refund_order_num,
            refund_order_amount,
            refund_payment_count,
            refund_payment_num,
            refund_payment_amount,
            coupon_get_count,
            coupon_using_count,
            coupon_used_count,
            appraise_good_count,
            appraise_mid_count,
            appraise_bad_count,
            appraise_default_count
        from dws_user_action_daycount
        where dt=date_add('2021-06-17',-30)
    )30d_ago
    on old.user_id=30d_ago.user_id;
