-- 地区主题

USE gmall;

insert overwrite table dwt_area_topic partition (dt = '2021-06-16')
select id,
       nvl(visit_last_1d_count, 0),
       nvl(login_last_1d_count, 0),
       nvl(visit_last_7d_count, 0),
       nvl(login_last_7d_count, 0),
       nvl(visit_last_30d_count, 0),
       nvl(login_last_30d_count, 0),
       nvl(visit_count, 0),
       nvl(login_count, 0),
       nvl(order_last_1d_count, 0),
       nvl(order_last_1d_original_amount, 0),
       nvl(order_last_1d_final_amount, 0),
       nvl(order_last_7d_count, 0),
       nvl(order_last_7d_original_amount, 0),
       nvl(order_last_7d_final_amount, 0),
       nvl(order_last_30d_count, 0),
       nvl(order_last_30d_original_amount, 0),
       nvl(order_last_30d_final_amount, 0),
       nvl(order_count, 0),
       nvl(order_original_amount, 0),
       nvl(order_final_amount, 0),
       nvl(payment_last_1d_count, 0),
       nvl(payment_last_1d_amount, 0),
       nvl(payment_last_7d_count, 0),
       nvl(payment_last_7d_amount, 0),
       nvl(payment_last_30d_count, 0),
       nvl(payment_last_30d_amount, 0),
       nvl(payment_count, 0),
       nvl(payment_amount, 0),
       nvl(refund_order_last_1d_count, 0),
       nvl(refund_order_last_1d_amount, 0),
       nvl(refund_order_last_7d_count, 0),
       nvl(refund_order_last_7d_amount, 0),
       nvl(refund_order_last_30d_count, 0),
       nvl(refund_order_last_30d_amount, 0),
       nvl(refund_order_count, 0),
       nvl(refund_order_amount, 0),
       nvl(refund_payment_last_1d_count, 0),
       nvl(refund_payment_last_1d_amount, 0),
       nvl(refund_payment_last_7d_count, 0),
       nvl(refund_payment_last_7d_amount, 0),
       nvl(refund_payment_last_30d_count, 0),
       nvl(refund_payment_last_30d_amount, 0),
       nvl(refund_payment_count, 0),
       nvl(refund_payment_amount, 0)
from (
         select id
         from dim_base_province
     ) t1
         left join
     (
         select province_id                                                          province_id,
                sum(if(dt = '2021-06-16', visit_count, 0))                           visit_last_1d_count,
                sum(if(dt = '2021-06-16', login_count, 0))                           login_last_1d_count,
                sum(if(dt >= date_add('2021-06-16', -6), visit_count, 0))            visit_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), login_count, 0))            login_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -29), visit_count, 0))           visit_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), login_count, 0))           login_last_30d_count,
                sum(visit_count)                                                     visit_count,
                sum(login_count)                                                     login_count,
                sum(if(dt = '2021-06-16', order_count, 0))                           order_last_1d_count,
                sum(if(dt = '2021-06-16', order_original_amount, 0))                 order_last_1d_original_amount,
                sum(if(dt = '2021-06-16', order_final_amount, 0))                    order_last_1d_final_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_count, 0))            order_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), order_original_amount, 0))  order_last_7d_original_amount,
                sum(if(dt >= date_add('2021-06-16', -6), order_final_amount, 0))     order_last_7d_final_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_count, 0))           order_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), order_original_amount, 0)) order_last_30d_original_amount,
                sum(if(dt >= date_add('2021-06-16', -29), order_final_amount, 0))    order_last_30d_final_amount,
                sum(order_count)                                                     order_count,
                sum(order_original_amount)                                           order_original_amount,
                sum(order_final_amount)                                              order_final_amount,
                sum(if(dt = '2021-06-16', payment_count, 0))                         payment_last_1d_count,
                sum(if(dt = '2021-06-16', payment_amount, 0))                        payment_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), payment_count, 0))          payment_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), payment_amount, 0))         payment_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), payment_count, 0))         payment_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), payment_amount, 0))        payment_last_30d_amount,
                sum(payment_count)                                                   payment_count,
                sum(payment_amount)                                                  payment_amount,
                sum(if(dt = '2021-06-16', refund_order_count, 0))                    refund_order_last_1d_count,
                sum(if(dt = '2021-06-16', refund_order_amount, 0))                   refund_order_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_count, 0))     refund_order_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), refund_order_amount, 0))    refund_order_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_count, 0))    refund_order_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), refund_order_amount, 0))   refund_order_last_30d_amount,
                sum(refund_order_count)                                              refund_order_count,
                sum(refund_order_amount)                                             refund_order_amount,
                sum(if(dt = '2021-06-16', refund_payment_count, 0))                  refund_payment_last_1d_count,
                sum(if(dt = '2021-06-16', refund_payment_amount, 0))                 refund_payment_last_1d_amount,
                sum(if(dt >= date_add('2021-06-16', -6), refund_payment_count, 0))   refund_payment_last_7d_count,
                sum(if(dt >= date_add('2021-06-16', -6), refund_payment_amount, 0))  refund_payment_last_7d_amount,
                sum(if(dt >= date_add('2021-06-16', -29), refund_payment_count, 0))  refund_payment_last_30d_count,
                sum(if(dt >= date_add('2021-06-16', -29), refund_payment_amount, 0)) refund_payment_last_30d_amount,
                sum(refund_payment_count)                                            refund_payment_count,
                sum(refund_payment_amount)                                           refund_payment_amount
         from dws_area_stats_daycount
         group by province_id
     ) t2
     on t1.id = t2.province_id;
